{'structure': ['time','rssi','x','y', 'h', 'temperature', 'pressure', 'pm25', 'pm10'],
'new_structure':{'T':'temperature', 'P':'pressure', 'X':'X', 'Y':'Y', '@':'time',
'A':'a', 'B':'b', 'C':'c', 'R':'rssi'}}
